// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jansyseafqmyrwuiskxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphbnN5c2VhZnFteXJ3dWlza3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzI4NjEsImV4cCI6MjA2OTIwODg2MX0.NXPWPn8-8epWwt9vrGl-_oJX4tdrTbILXDnVzKkzuCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});